packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  msw: false
  bcrypt: true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true

minimumReleaseAgeExclude:
  - '@hookform/resolvers@5.7.1'
